name: Sign, Notarize and Package Petoi Desktop App

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App name in DMG (e.g., Petoi Desktop App.app)'
        required: true
        default: 'Petoi Desktop App.app'
      app_version:
        description: 'App version (used in DMG filename)'
        required: true
        default: '1.2.5'

jobs:
  build-and-package:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip Application
        run: unzip mac/Petoi\ Desktop\ App.zip -d mac/

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Import Developer Certificates
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.MAC_CERTIFICATE_DATA }}
          p12-password: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
      
      - name: Verify Installer Certificate
        run: |
          security find-identity -v | grep "Developer ID Application: Petoi LLC (H98JHTT3JH)"
          if [ $? -ne 0 ]; then
            echo "Error: 未找到有效的签名证书"
            exit 1
          fi
      
      - name: Code Sign the Application (覆盖所有嵌套二进制文件)
        run: |
          set -ex
          APP_PATH="mac/${{ github.event.inputs.app_name }}"
          echo "Signing application at path: $APP_PATH"
          
          if [ ! -d "$APP_PATH" ]; then
            echo "Error: Application not found at path $APP_PATH"
            exit 1
          fi

          # 关键优化：递归查找所有需要签名的文件
          # 包含：.dylib 动态库、.so 扩展模块、所有可执行文件
          find "$APP_PATH" -type f \( \
            -name "*.dylib" -o \
            -name "*.so" -o \
            -perm +x \
          \) -print0 | while IFS= read -r -d '' file; do
            echo "Signing file: $file"
            codesign --force --timestamp -o runtime \
              --sign "Developer ID Application: Petoi LLC (H98JHTT3JH)" \
              "$file"
          done
          
          # 最终对整个.app进行深度签名（确保签名链完整）
          codesign --force --deep --strict --sign "Developer ID Application: Petoi LLC (H98JHTT3JH)" \
            --options runtime \
            --timestamp "$APP_PATH"

      - name: Verify .app Signature (仅验证签名完整性)
        run: |
          APP_PATH="mac/${{ github.event.inputs.app_name }}"
          codesign --verify --deep --verbose=4 "$APP_PATH"

      - name: Verify Critical Paths (确保嵌套文件已签名)
        run: |
          APP_PATH="mac/${{ github.event.inputs.app_name }}"
          echo "Verifying critical paths for proper signing..."
          
          # 验证Python依赖目录下的文件
          find "$APP_PATH/Contents/Resources" \( -name "*.dylib" -o -name "*.so" -o -perm +x \) -type f | while read -r file; do
            echo "Checking signature for: $file"
            codesign --verify --verbose=1 "$file"
            if [ $? -ne 0 ]; then
              echo "❌ 签名验证失败: $file"
              exit 1
            fi
          done
          echo "✅ 所有关键路径文件签名验证通过"

      - name: Create DMG
        run: |
          mkdir -p dist/dmg
          cp -R "mac/${{ github.event.inputs.app_name }}" dist/dmg/
          ln -s /Applications dist/dmg/Applications
          
          create-dmg \
            --volname "Petoi Desktop App" \
            --background "mac/Make_for_dmg.jpg" \
            --window-pos 400 200 \
            --window-size 940 580 \
            --icon-size 100 \
            --icon "${{ github.event.inputs.app_name }}" 180 200 \
            --app-drop-link 420 200 \
            --no-internet-enable \
            "dist/Petoi_Desktop_App_${{ github.event.inputs.app_version }}.dmg" \
            "dist/dmg/"

      - name: Notarize the DMG (含详细日志查询)
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PWD: ${{ secrets.APPLE_ID_PWD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          DMG_PATH="dist/Petoi_Desktop_App_${{ github.event.inputs.app_version }}.dmg"
          echo "Submitting DMG for notarization: $DMG_PATH"
          
          # 提交公证并捕获完整输出
          SUBMISSION_OUTPUT=$(xcrun notarytool submit "$DMG_PATH" \
            --apple-id "$APPLE_ID" \
            --password "$APPLE_ID_PWD" \
            --team-id "$APPLE_TEAM_ID" \
            --wait \
            --verbose 2>&1)
          
          # 打印提交结果
          echo "$SUBMISSION_OUTPUT"
          
          # 提取Submission ID
          SUBMISSION_ID=$(echo "$SUBMISSION_OUTPUT" | grep -oE 'id: [0-9a-f-]+' | cut -d' ' -f2 | head -n1)
          echo "Extracted Submission ID: $SUBMISSION_ID"
          
          # 强制查询并打印详细日志
          if [ -n "$SUBMISSION_ID" ]; then
            echo "=== 公证详细日志 ==="
            xcrun notarytool log "$SUBMISSION_ID" \
              --apple-id "$APPLE_ID" \
              --password "$APPLE_ID_PWD" \
              --team-id "$APPLE_TEAM_ID"
            echo "===================="
          else
            echo "❌ 无法提取Submission ID，无法查询日志"
            exit 1
          fi
          
          # 检查公证是否成功
          if echo "$SUBMISSION_OUTPUT" | grep -q "status: Accepted"; then
            echo "✅ Notarization succeeded. Stapling ticket..."
            xcrun stapler staple "$DMG_PATH"
            xcrun stapler validate "$DMG_PATH"
          else
            echo "❌ Notarization failed. Check log above for details."
            exit 1
          fi

      - name: Final Verification
        run: |
          DMG_PATH="dist/Petoi_Desktop_App_${{ github.event.inputs.app_version }}.dmg"
          MOUNT_POINT=$(hdiutil mount "$DMG_PATH" | grep -o '/Volumes/[^ ]*' | head -n 1)
          
          APP_IN_DMG="$MOUNT_POINT/${{ github.event.inputs.app_name }}"
          echo "Verifying final app in DMG: $APP_IN_DMG"
          spctl --assess --type execute --verbose "$APP_IN_DMG"
          
          hdiutil unmount "$MOUNT_POINT"

      - name: Upload Signed DMG
        uses: actions/upload-artifact@v4
        with:
          name: Petoi_Desktop_App_${{ github.event.inputs.app_version }}.dmg
          path: dist/Petoi_Desktop_App_${{ github.event.inputs.app_version }}.dmg
          retention-days: 30
